# Generated by Django 5.1.4 on 2025-01-10 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 24, 9, 344644))),
            ],
        ),
    ]
