# Generated by Django 5.1.4 on 2025-01-10 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 16, 25, 23, 108114)),
        ),
    ]
