# Generated by Django 5.1.4 on 2025-01-13 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_usermodel_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 15, 57, 37, 535151)),
        ),
    ]
