# Generated by Django 5.1.4 on 2025-01-16 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_usermodel_entry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(upload_to='procucts_images/')),
                ('desxription', models.TextField(max_length=160)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 0, 24, 26, 51173)),
        ),
    ]
